name: Notify Parent Repo

on:
  push:
    branches:
      - main

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Parent Repo Sync
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PARENT_REPO_TOKEN }}
          script: |
            const parentRepo = '${{ vars.PARENT_REPO || 'devmaster-x/ex_parent' }}';
            const workflowId = 'sync.yml';
            
            try {
              await github.rest.actions.createWorkflowDispatch({              
                owner: parentRepo.split('/')[0],
                repo: parentRepo.split('/')[1],
                workflow_id: workflowId,
                ref: 'main'
              });
              console.log(`Successfully triggered ${workflowId} in parent repo: ${parentRepo}`);
            } catch (error) {
              console.error('Failed to trigger parent repo sync:', error.message);
              core.setFailed(`Failed to trigger sync: ${error.message}`);
            }